FE/pages/_components/button/Button.tsx
FE/pages/index.tsx

[FE] 네이버 소셜 로그인 연결

---

.github/workflows/backend.yml
.github/workflows/frontend.yml
FE/Dockerfile

close #13 
- 프론트엔드 도커파일 내용을 수정했습니다.
- `main`에서 `develop`으로 action 브랜치를 수정했습니다.

[BE] Dockfile 수정

---

BE/src/main/java/com/twopilogue/intervyou/config/jwt/JwtProvider.java
BE/src/main/java/com/twopilogue/intervyou/user/constant/UserConstant.java
BE/src/main/java/com/twopilogue/intervyou/user/dto/response/LoginResponse.java
BE/src/main/java/com/twopilogue/intervyou/user/entity/User.java
BE/src/main/java/com/twopilogue/intervyou/user/repository/UserRepository.java
BE/src/main/java/com/twopilogue/intervyou/user/service/UserService.java

close #20 
1. 유저 엔티티에 닉네임 추가
2. 회원가입 시 닉네임 생성
- `관형사 + 동물이름 + 0~9999 사이 숫자`로 닉네임 생성

[BE] 사용자 닉네임 추가

---

BE/build.gradle
BE/src/main/java/com/twopilogue/intervyou/community/constant/CommunityConstant.java
BE/src/main/java/com/twopilogue/intervyou/community/controller/CommunityController.java
BE/src/main/java/com/twopilogue/intervyou/community/dto/request/WritePostRequest.java
BE/src/main/java/com/twopilogue/intervyou/community/dto/response/WritePostResponse.java
BE/src/main/java/com/twopilogue/intervyou/community/entity/Community.java
BE/src/main/java/com/twopilogue/intervyou/community/repositiry/CommunityRepository.java
BE/src/main/java/com/twopilogue/intervyou/community/service/CommunityService.java

close #19 
1. 게시글(`Community`)엔티티 생성
2. 게시글 등록 API 구현

[BE] 게시글 등록 API 구현

---

.github/workflows/backend.yml
.github/workflows/frontend.yml

[BE] actions 동작 브랜치 변경

---

FE/src/app/_components/header/Header.tsx
FE/src/app/_components/input/SearchField.tsx
FE/src/app/board/BoardFrame.tsx
FE/src/app/board/BoardItem.tsx
FE/src/app/board/Pagination.tsx
FE/src/app/board/page.tsx
FE/src/app/chat/_components/Header/index.tsx

close #37 
- 최대 너비 1440px로 설정.
- 동작은 API 연결 후 !

[FE] 커뮤니티 목록 컴포넌트 생성

---

FE/src/app/board/create/TextArea.tsx
FE/src/app/board/create/page.tsx
FE/src/app/board/page.tsx

close #39 
- TextArea를 기존 공통으로 만들어둔 컴포넌트와 분리했음. 
- 최대한 공통으로 사용할 수 있도록 만들고 싶으나, 1) 채팅방에서 사용 시 특정 높이 이상이 되면 제한되어야 함. 2) 게시글 작성 시 최대로 늘려야 함. 의 경우를 생각해야 하는데, 아예 분리해서 사용하는 것이 좋을지, 공통으로 만들어 경우의 수를 나누는게 좋을지 잘 모르겠다. 우선 분리해서 사용하는 방향으로 생각 중이다.

[FE] 커뮤니티 게시글 작성 컴포넌트 생성

---

BE/src/main/java/com/twopilogue/intervyou/community/controller/CommunityController.java
BE/src/main/java/com/twopilogue/intervyou/community/repositiry/CommunityRepository.java
BE/src/main/java/com/twopilogue/intervyou/community/service/CommunityService.java

close #49 
1. 게시글 조회 시 삭제된 게시글까지 조회되는 이슈를 해결했습니다.

[BE] 내가 등록한 게시글 목록 조회 API 구현

---

BE/src/main/java/com/twopilogue/intervyou/community/constant/CommunityConstant.java
BE/src/main/java/com/twopilogue/intervyou/community/controller/CommunityController.java
BE/src/main/java/com/twopilogue/intervyou/community/dto/response/CommentListDtoResponse.java
BE/src/main/java/com/twopilogue/intervyou/community/dto/response/CommentListResponse.java
BE/src/main/java/com/twopilogue/intervyou/community/repositiry/CommentRepository.java
BE/src/main/java/com/twopilogue/intervyou/community/service/CommunityService.java

[BE] 내가 등록한 댓글 목록 조회

---

BE/src/main/java/com/twopilogue/intervyou/community/entity/Comment.java
BE/src/main/java/com/twopilogue/intervyou/community/service/CommunityService.java

[BE] 사용하지 않는 엔티티 필드 삭제

---

FE/src/app/board/create/page.tsx
FE/src/app/board/detail/CommentItem.tsx
FE/src/app/board/detail/[pageId]/page.tsx

[FE] 커뮤니티 게시글 조회 컴포넌트 생성

---

BE/src/main/java/com/twopilogue/intervyou/interview/constant/InterviewConstant.java
BE/src/main/java/com/twopilogue/intervyou/interview/controller/InterviewController.java
BE/src/main/java/com/twopilogue/intervyou/interview/dto/response/CheckOngoingInterviewResponse.java
BE/src/main/java/com/twopilogue/intervyou/interview/repository/InterviewRepository.java
BE/src/main/java/com/twopilogue/intervyou/interview/service/InterviewService.java

[BE] 진행중인 면접 체크 API 구현

---

BE/src/main/java/com/twopilogue/intervyou/interview/constant/InterviewConstant.java
BE/src/main/java/com/twopilogue/intervyou/interview/controller/InterviewController.java
BE/src/main/java/com/twopilogue/intervyou/interview/dto/response/InterviewContentResponse.java
BE/src/main/java/com/twopilogue/intervyou/interview/dto/response/StartInterviewResponse.java
BE/src/main/java/com/twopilogue/intervyou/interview/repository/InterviewSequenceRepository.java
BE/src/main/java/com/twopilogue/intervyou/interview/service/InterviewService.java

[BE] 진행중인 면접 기록 조회 API 구현

---

BE/src/main/java/com/twopilogue/intervyou/interview/constant/InterviewConstant.java
BE/src/main/java/com/twopilogue/intervyou/interview/controller/InterviewController.java
BE/src/main/java/com/twopilogue/intervyou/interview/entity/Interview.java
BE/src/main/java/com/twopilogue/intervyou/interview/exception/InterviewErrorResult.java
BE/src/main/java/com/twopilogue/intervyou/interview/service/InterviewService.java

[BE] 면접 종료 API 구현

---

FE/package-lock.json
FE/package.json
FE/src/app/_components/header/Header.tsx
FE/src/app/login/Redirect.tsx
FE/src/app/login/page.tsx
FE/src/app/mypage/page.tsx
FE/src/slices/auth.slice.ts

close #61 
- 상태 관리 라이브러리 zustand 사용 및 환경 설정
- 로그인 후 텍스트가 변경되는 과정에서 깜빡임이 있는데, 어떻게 해결할 수 있을까?

[FE] 소셜 로그인 API 연결

---

BE/src/main/java/com/twopilogue/intervyou/interview/constant/InterviewConstant.java
BE/src/main/java/com/twopilogue/intervyou/interview/controller/InterviewController.java
BE/src/main/java/com/twopilogue/intervyou/interview/dto/request/StartInterviewRequest.java
BE/src/main/java/com/twopilogue/intervyou/interview/exception/InterviewErrorResult.java
BE/src/main/java/com/twopilogue/intervyou/interview/repository/InterviewRepository.java
BE/src/main/java/com/twopilogue/intervyou/interview/repository/InterviewSequenceRepository.java
BE/src/main/java/com/twopilogue/intervyou/interview/service/InterviewService.java

close #80 
1. 프롬프트의 내용을 일부 수정했습니다.
- 높임말 사용
- 일부 표현 명확화
- 문장 구분
2. 이전 면접 기록 삭제 API를 구현했습니다.

[BE] 이전 면접 기록 삭제 API 구현

---

BE/src/main/java/com/twopilogue/intervyou/interview/constant/InterviewConstant.java
BE/src/main/java/com/twopilogue/intervyou/interview/controller/InterviewController.java
BE/src/main/java/com/twopilogue/intervyou/interview/dto/response/InterviewRecordListResponse.java
BE/src/main/java/com/twopilogue/intervyou/interview/dto/response/InterviewRecordResponse.java
BE/src/main/java/com/twopilogue/intervyou/interview/repository/InterviewRepository.java
BE/src/main/java/com/twopilogue/intervyou/interview/service/InterviewService.java

[BE] 이전 면접 기록 목록 조회 API 구현

---

BE/src/main/java/com/twopilogue/intervyou/interview/constant/InterviewConstant.java
BE/src/main/java/com/twopilogue/intervyou/interview/controller/InterviewController.java
BE/src/main/java/com/twopilogue/intervyou/interview/dto/response/InterviewResponse.java
BE/src/main/java/com/twopilogue/intervyou/interview/exception/InterviewErrorResult.java
BE/src/main/java/com/twopilogue/intervyou/interview/service/InterviewService.java

close #87 
1. 진행중인 면접 기록 조회와 이전 면접 기록 조회 로직이 중복되어 하나로 결합했습니다.

[BE] 면접 기록 조회 API 구현

---

FE/src/app/_components/header/Header.tsx
FE/src/app/_components/modal/alert/AlertItem.tsx
FE/src/app/_components/modal/alert/ModalAlert.tsx
FE/src/app/_components/modal/menu/ModalMenu.tsx
FE/src/app/mypage/page.tsx

close #90 
- 모바일/PC 환경에 따라 알림창의 크기가 달라짐.
- 모바일 -> 전체 화면
- PC -> 오른쪽 일부 화면

[FE] 알림창 컴포넌트 생성

---

FE/src/app/not-found.tsx

[FE] 404 페이지 컴포넌트 생성

---

BE/build.gradle

[BE] mysql 의존성 추가
